//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.17929
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTransferCoreImpl.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentTransferCoreImpl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _轉入_mask_add_64 {
            get {
                object obj = ResourceManager.GetObject("_轉入_mask_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _轉入轉出確認layers_ok_64 {
            get {
                object obj = ResourceManager.GetObject("_轉入轉出確認layers_ok_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _轉出_image_size_up_64 {
            get {
                object obj = ResourceManager.GetObject("_轉出_image_size_up_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立育才國小&quot; Code=&quot;011601&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立聖心國小&quot; Code=&quot;011602&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立及人國小&quot; Code=&quot;011603&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立竹林國小&quot; Code=&quot;011604&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立信賢種籽親子實小&quot; Code=&quot;011606&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立裕德國小&quot; Code=&quot;011607&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國小&quot; Code=&quot;014601&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立國光國小&quot; Code=&quot;014602&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string eh {
            get {
                return ResourceManager.GetString("eh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Fields&gt;
        ///    &lt;!--這個對照表是用於匯出 Excel 時用的--&gt;
        ///    &lt;Field Pattern=&quot;EnglishName&quot; Chinese=&quot;英文姓名&quot;/&gt;
        ///    &lt;Field Pattern=&quot;BirthPlace&quot; Chinese=&quot;出生地&quot;/&gt;
        ///    &lt;Field Pattern=&quot;PermanentAddress/AddressList/Address[1]&quot; Chinese=&quot;戶籍地址&quot; DataParser=&quot;Address&quot;/&gt;
        ///    &lt;Field Pattern=&quot;MailingAddress/AddressList/Address[1]&quot; Chinese=&quot;聯絡地址&quot; DataParser=&quot;Address&quot;/&gt;
        ///    &lt;Field Pattern=&quot;OtherAddress/AddressList/Address[1]&quot; Chinese=&quot;其他地址1&quot; DataParser=&quot;Address&quot;/&gt;
        ///    &lt;Field Pattern=&quot;OtherAddress/AddressList/Address[2]&quot; Chinese=&quot;其他地址2&quot; D [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ExportNameMap {
            get {
                return ResourceManager.GetString("ExportNameMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立時雨國中&quot; Code=&quot;011501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國中&quot; Code=&quot;014501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立重慶國中&quot; Code=&quot;014503&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立江翠國中&quot; Code=&quot;014504&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立中山國中&quot; Code=&quot;014505&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新埔國中&quot; Code=&quot;014506&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新莊國中&quot; Code=&quot;014507&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新泰國中&quot; Code=&quot;014508&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string jh {
            get {
                return ResourceManager.GetString("jh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap live_update_up_128 {
            get {
                object obj = ResourceManager.GetObject("live_update_up_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;OptionList&gt;
        ///    &lt;Options Name=&quot;學生身份註記&quot;&gt;
        ///        &lt;Item&gt;一般學生&lt;/Item&gt;
        ///        &lt;Item&gt;本人身障&lt;/Item&gt;
        ///        &lt;Item&gt;家長身障&lt;/Item&gt;
        ///        &lt;Item&gt;低收入戶&lt;/Item&gt;
        ///        &lt;Item&gt;大陸來台依親者&lt;/Item&gt;
        ///        &lt;Item&gt;功勳子女&lt;/Item&gt;
        ///        &lt;Item&gt;海外僑生&lt;/Item&gt;
        ///        &lt;Item&gt;港澳生&lt;/Item&gt;
        ///        &lt;Item&gt;邊疆生&lt;/Item&gt;
        ///        &lt;Item&gt;原住民&lt;/Item&gt;
        ///        &lt;Item&gt;外籍生&lt;/Item&gt;
        ///        &lt;Item&gt;資優生&lt;/Item&gt;
        ///        &lt;Item&gt;派外人員子女&lt;/Item&gt;
        ///        &lt;Item&gt;體育績優&lt;/Item&gt;
        ///        &lt;Item&gt;顏面傷殘&lt;/Item&gt;
        ///        &lt;Item&gt;教職員子女&lt;/Item&gt;
        ///        &lt;Item&gt;公教遺族-因公&lt;/Item&gt;
        ///       [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Fields&gt;
        ///    &lt;!--這個對照表是用於轉出學生基本資料時用的--&gt;
        ///    &lt;Field PhysicalName=&quot;english_name&quot; EnglishName=&quot;EnglishName&quot; IsXmlContent=&quot;false&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;birth_place&quot; EnglishName=&quot;BirthPlace&quot; IsXmlContent=&quot;false&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;mailing_address&quot; EnglishName=&quot;MailingAddress&quot; IsXmlContent=&quot;true&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;other_addresses&quot; EnglishName=&quot;OtherAddress&quot; IsXmlContent=&quot;true&quot;/&gt;
        ///    &lt;Field PhysicalName=&quot;permanent_address&quot; EnglishName=&quot;PermanentAddress&quot; IsXmlContent=&quot;true&quot;/&gt;
        ///    &lt;Field [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string StudentFields {
            get {
                return ResourceManager.GetString("StudentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 綜合資料轉移單 {
            get {
                object obj = ResourceManager.GetObject("綜合資料轉移單", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
